name: Google Form Trigger

on:
  workflow_dispatch:
  repository_dispatch:
    types: [google_form_event]

#やりたいこと
# Form入力して送信
# 新規ブランチを作成
# 特定ファイルの編集（末尾に定型文 + 変数）を追記
# Terraform fmt --recurcive で整形
# PRを作成

jobs:
  handle_google_form_event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Process form data （具体的なファイル操作）# ここで変更を加えるスクリプトやコマンドを追加
        run: |
          echo "Sample change" >> file.txt
          echo "${{ github.event.client_payload.field1 }}" > data.txt
          echo "${{ github.event.client_payload.field2 }}" >> data.txt
          date +%s > report.txt

      - name: Create a new branch
        run: |
          git config --global user.name "otake-shol"
          git config --global user.email "otkshol@gmail.com"
          git remote set-url origin https://x-access-token:${{secrets.GHA_TOKEN}}@github.com/otake-shol/auto-create-PR-by-GHA
          git checkout -b feature-add-cidr-block-by-hoge
          git add .
          git commit -m "Add sample change"
          git push https://x-access-token:${{secrets.GHA_TOKEN}}@github.com/otake-shol/auto-create-PR-by-GHA feature-add-cidr-block-by-hoge

      - name: Create Pull Request （参照 https://github.com/marketplace/actions/create-pull-request）
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GHA_TOKEN }}
          commit-message: 依頼先からのIP穴あけ対応・SSM設定追加
          committer: otake-shol <otkshol@gmail.com>
          author: otake-shol <otkshol@gmail.com>
          title: 依頼先からのIP穴あけ対応
          body: Automatic PR created from Google Form submission.
          branch: feature-add-cidr-block-by
          base: master
          delete-branch: true
