name: "Hello deploy"

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  preview:
    name: "Hello"
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello world"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Process form data （具体的なファイル操作）
        run: |
          date +%s > test.txt

      - name: Create Pull Request （参照 https://github.com/marketplace/actions/create-pull-request）
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: ${依頼先}からのIP穴あけ対応
          committer: GitHub <noreply@github.com>
          author: Your Name <your-email@example.com>
          title: ${依頼先}からのIP穴あけ対応
          body: Automatic PR created from Google Form submission.
          branch: feature-add-cidr-block-by-{依頼先}
          base: develop
          label: #好みでつける

